sudo: true
language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -q
  - sh CI/install-mpi.sh openmpi
install:
  - svn co -r 14624 svn://svn.lammps.org/lammps-ro/trunk/src lammps_src
  - cd lammps_src
  - make yes-kspace
  - make yes-manybody
  - ln -s .. USER-GFMD
  - make yes-user-gfmd
  - cp USER-GFMD/CI/Makefile.CI MAKE/MINE
  - make CI
  - cd USER-GFMD
  - make unittests
script:
  - ./unittests
  - cd tests ; sh run_tests.sh ../../lmp_CI
