sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
env:
  - LAMMPS_REV=14624
before_install:
  - sudo apt-get update -q
  - sh CI/install-mpi.sh openmpi
  - sudo apt-get -y install libfftw3-3 libfftw3-dev
install:
  - mkdir USER-GFMD
  - mv * USER-GFMD || true
  - mkdir LAMMPS
  - cd LAMMPS
  - svn co -r $LAMMPS_REV svn://svn.lammps.org/lammps-ro/trunk/src src
  - svn co -r $LAMMPS_REV svn://svn.lammps.org/lammps-ro/trunk/tools tools
  - cd src
  - make yes-kspace
  - make yes-manybody
  - mv ../../USER-GFMD .
  - make yes-user-gfmd
  - cp USER-GFMD/CI/Makefile.CI_serial MAKE/MINE
  - make mpi-stubs
  - make CI_serial
  - cd USER-GFMD
  - make unittests
script:
  - ./unittests
#  - $TRAVIS_BUILD_DIR/LAMMPS/src/lmp_CI_serial -h
  - cd tests
  - bash run_tests.sh $TRAVIS_BUILD_DIR/LAMMPS/src/lmp_CI_serial
