sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
env:
  - LAMMPS_REV=14624
before_install:
  - sudo apt-get update -q
  - sh CI/install-mpi.sh openmpi
  - sudo apt-get -y install libfftw3-3 libfftw3-dev
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - python setup.py install
install:
  - mkdir USER-GFMD
  - mv * USER-GFMD || true
  - mkdir LAMMPS
  - cd LAMMPS
  - svn co -r $LAMMPS_REV svn://svn.lammps.org/lammps-ro/trunk/src src
  - svn co -r $LAMMPS_REV svn://svn.lammps.org/lammps-ro/trunk/tools tools
  - cd src
  - make yes-kspace
  - make yes-manybody
  - mv ../../USER-GFMD .
  - make yes-user-gfmd
  - cp USER-GFMD/CI/Makefile.CI_serial MAKE/MINE
  - make mpi-stubs
  - make CI_serial
  - cd USER-GFMD
  - make unittests
script:
  - ./unittests
#  - $TRAVIS_BUILD_DIR/LAMMPS/src/lmp_CI_serial -h
  - cd tests
  - bash run_tests.sh $TRAVIS_BUILD_DIR/LAMMPS/src/lmp_CI_serial
