# Check which files have been changed

diff -q ../linearalgebra.cpp mathutils/linearalgebra.cpp
diff -q ../geometry.cpp stiffnesskernels/geometry.cpp
diff -q ../li_berger.cpp stiffnesskernels/li_berger.cpp
diff -q ../table2d.cpp mathutils/table2d.cpp
diff -q ../atom_vec_gfmd.cpp atom_vec_gfmd.cpp
diff -q ../gfmd_solver.cpp gfmd_solver.cpp
diff -q ../gfmd_solver_fft.cpp solvers/gfmd_solver_fft.cpp
diff -q ../gfmd_solver_static.cpp solvers/gfmd_solver_static.cpp
diff -q ../gfmd_solver_dynamic.cpp solvers/gfmd_solver_dynamic.cpp
diff -q ../gfmd_solver_cuda.cpp solvers/gfmd_solver_cuda.cpp
diff -q ../gfmd_analyzer.cpp extras/gfmd_analyzer.cpp
diff -q ../surface_stiffness.cpp surface_stiffness.cpp
diff -q ../debug_stiffness.cpp stiffnesskernels/debug_stiffness.cpp
diff -q ../isotropic_stiffness.cpp stiffnesskernels/isotropic_stiffness.cpp
diff -q ../nonperiodic_stiffness.cpp stiffnesskernels/nonperiodic_stiffness.cpp
diff -q ../sc100_stiffness.cpp stiffnesskernels/sc100_stiffness.cpp
diff -q ../fcc100_stiffness.cpp stiffnesskernels/fcc100_stiffness.cpp
diff -q ../fcc100ft_stiffness.cpp stiffnesskernels/fcc100ft_stiffness.cpp
diff -q ../fcc100fteam_stiffness.cpp stiffnesskernels/fcc100fteam_stiffness.cpp
diff -q ../crystal_surface.cpp crystal_surface.cpp
diff -q ../dia100_surface.cpp surfaces/dia100_surface.cpp
diff -q ../dia111_surface.cpp surfaces/dia111_surface.cpp
diff -q ../fcc100_surface.cpp surfaces/fcc100_surface.cpp
diff -q ../fcc111_surface.cpp surfaces/fcc111_surface.cpp
diff -q ../sc100_surface.cpp surfaces/sc100_surface.cpp
diff -q ../ft_stiffness.cpp stiffnesskernels/ft_stiffness.cpp
diff -q ../force_constants.cpp force_constants.cpp
diff -q ../fc_atomistica_fd.cpp forceconstants/fc_atomistica_fd.cpp
diff -q ../fc_pair_potential.cpp forceconstants/fc_pair_potential.cpp
diff -q ../fc_finite_differences.cpp forceconstants/fc_finite_differences.cpp
diff -q ../fc_eam.cpp forceconstants/fc_eam.cpp
diff -q ../fc_eam_fd.cpp forceconstants/fc_eam_fd.cpp
diff -q ../fc_lj_cut.cpp forceconstants/fc_lj_cut.cpp
diff -q ../fc_lj_cut_fd.cpp forceconstants/fc_lj_cut_fd.cpp
diff -q ../fc_lj_smooth.cpp forceconstants/fc_lj_smooth.cpp
diff -q ../fc_tersoff.cpp forceconstants/fc_tersoff.cpp
diff -q ../pair_eam_gf.cpp forceconstants/pair_eam_gf.cpp
diff -q ../pair_lj_cut_gf.cpp forceconstants/pair_lj_cut_gf.cpp
diff -q ../pair_tersoff_gf.cpp forceconstants/pair_tersoff_gf.cpp
diff -q ../gfmd_misc.cpp gfmd_misc.cpp
diff -q ../fix_gfmd.cpp fix_gfmd.cpp
diff -q ../fix_gfmd_cuda.cpp fix_gfmd_cuda.cpp
diff -q ../fix_contact_rigid.cpp extras/fix_contact_rigid.cpp
diff -q ../fix_contact_sphere.cpp extras/fix_contact_sphere.cpp
diff -q ../fix_wall_map.cpp extras/fix_wall_map.cpp
#diff -q ../min_cg_gfmd.cpp min_cg_gfmd.cpp
#diff -q ../min_tr_gfmd.cpp min_tr_gfmd.cpp
diff -q ../displace_xeq.cpp extras/displace_xeq.cpp
diff -q ../fix_addforce_dynamic.cpp extras/fix_addforce_dynamic.cpp

diff -q ../gfmd_solver_cuda_kernel.cu cuda/gfmd_solver_cuda_kernel.cu
diff -q ../fix_gfmd_cuda_kernel.cu cuda/fix_gfmd_cuda_kernel.cu
diff -q ../../lib/cuda/atom_vec_gfmd_cuda.cu cuda/atom_vec_gfmd_cuda.cu

diff -q ../fix_fire.cpp cuda/fix_fire.cpp
diff -q ../fix_fire_cuda.cpp cuda/fix_fire_cuda.cpp
diff -q ../fix_fire_cuda_kernel.cu cuda/fix_fire_cuda_kernel.cu

diff -q ../complexcomp.h mathutils/complexcomp.h
diff -q ../vec.h mathutils/vec.h
diff -q ../mat.h mathutils/mat.h
diff -q ../linearalgebra.h mathutils/linearalgebra.h
diff -q ../geometry.h stiffnesskernels/geometry.h
diff -q ../li_berger.h stiffnesskernels/li_berger.h
diff -q ../table2d.h mathutils/table2d.h
diff -q ../atom_vec_gfmd.h atom_vec_gfmd.h
diff -q ../gfmd_solver.h gfmd_solver.h
diff -q ../gfmd_solver_fft.h solvers/gfmd_solver_fft.h
diff -q ../gfmd_solver_static.h solvers/gfmd_solver_static.h
diff -q ../gfmd_solver_dynamic.h solvers/gfmd_solver_dynamic.h
diff -q ../gfmd_solver_cuda.h cuda/gfmd_solver_cuda.h
diff -q ../gfmd_analyzer.h extras/gfmd_analyzer.h
diff -q ../surface_stiffness.h surface_stiffness.h
diff -q ../debug_stiffness.h stiffnesskernels/debug_stiffness.h
diff -q ../isotropic_stiffness.h stiffnesskernels/isotropic_stiffness.h
diff -q ../nonperiodic_stiffness.h stiffnesskernels/nonperiodic_stiffness.h
diff -q ../sc100_stiffness.h stiffnesskernels/sc100_stiffness.h
diff -q ../fcc100_stiffness.h stiffnesskernels/fcc100_stiffness.h
diff -q ../fcc100ft_stiffness.h stiffnesskernels/fcc100ft_stiffness.h
diff -q ../fcc100fteam_stiffness.h stiffnesskernels/fcc100fteam_stiffness.h
diff -q ../ft_stiffness.h stiffnesskernels/ft_stiffness.h
diff -q ../crystal_surface.h crystal_surface.h
diff -q ../dia100_surface.h surfaces/dia100_surface.h
diff -q ../dia111_surface.h surfaces/dia111_surface.h
diff -q ../fcc100_surface.h surfaces/fcc100_surface.h
diff -q ../fcc111_surface.h surfaces/fcc111_surface.h
diff -q ../sc100_surface.h surfaces/sc100_surface.h
diff -q ../force_constants.h force_constants.h
diff -q ../fc_atomistica_fd.h forceconstants/fc_atomistica_fd.h
diff -q ../fc_pair_potential.h forceconstants/fc_pair_potential.h
diff -q ../fc_finite_differences.h forceconstants/fc_finite_differences.h
diff -q ../fc_eam.h forceconstants/fc_eam.h
diff -q ../fc_eam_fd.h forceconstants/fc_eam_fd.h
diff -q ../fc_lj_cut.h forceconstants/fc_lj_cut.h
diff -q ../fc_lj_cut_fd.h forceconstants/fc_lj_cut_fd.h
diff -q ../fc_lj_smooth.h forceconstants/fc_lj_smooth.h
diff -q ../fc_tersoff.h forceconstants/fc_tersoff.h
diff -q ../pair_eam_gf.h forceconstants/pair_eam_gf.h
diff -q ../pair_lj_cut_gf.h forceconstants/pair_lj_cut_gf.h
diff -q ../pair_tersoff_gf.h forceconstants/pair_tersoff_gf.h
diff -q ../gfmd_misc.h gfmd_misc.h
diff -q ../fix_gfmd.h fix_gfmd.h
diff -q ../fix_gfmd_cuda.h cuda/fix_gfmd_cuda.h
diff -q ../fix_contact_rigid.h extras/fix_contact_rigid.h
diff -q ../fix_contact_sphere.h extras/fix_contact_sphere.h
diff -q ../fix_wall_map.h extras/fix_wall_map.h
#diff -q ../min_cg_gfmd.h min_cg_gfmd.h
#diff -q ../min_tr_gfmd.h min_tr_gfmd.h
diff -q ../displace_xeq.h extras/displace_xeq.h
diff -q ../fix_addforce_dynamic.h extras/fix_addforce_dynamic.h

diff -q ../gfmd_solver_cuda_kernel.h cuda/gfmd_solver_cuda_kernel.h
diff -q ../fix_gfmd_cuda_kernel.h cuda/fix_gfmd_cuda_kernel.h
diff -q ../../lib/cuda/atom_vec_gfmd_cuda_cu.h cuda/atom_vec_gfmd_cuda_cu.h

diff -q ../gfmd_grid.h gfmd_grid.h

diff -q ../fix_fire.h cuda/fix_fire.h
diff -q ../fix_fire_cuda.h cuda/fix_fire_cuda.h
diff -q ../fix_fire_cuda_kernel.h cuda/fix_fire_cuda_kernel.h

diff -q ../STUBS/mpi.c mpi.c
diff -q ../STUBS/mpi.h mpi.h
