name: CI

on:
  push:
    branches:    
      - '*'
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update -qy
        sudo apt-get -y install software-properties-common strace libnuma-dev libssl-dev curl wget git bash make file pkg-config gcc g++ gfortran python3-dev python3-pip python3-numpy openmpi-bin libopenmpi-dev libnetcdf-pnetcdf-dev libfftw3-3 libfftw3-dev libfftw3-mpi-dev 
  
    - name: Compile
      run: |
        mkdir USER-GFMD
        mv * USER-GFMD || true
        mkdir LAMMPS
        cd LAMMPS
        svn co https://github.com/lammps/lammps.git/trunk/src src
        svn co https://github.com/lammps/lammps.git/trunk/tools tools
        cd src
        mv ../../USER-GFMD .
        sed -i 's/user-vtk user-yaff/user-vtk user-yaff user-gfmd/g' Makefile
        sed -i 's/FFT_INC =/FFT_INC = -DFFT_FFTW3/g' MAKE/OPTIONS/Makefile.g++_openmpi
        sed -i 's/FFT_LIB =/FFT_LIB = -lfftw3/g' MAKE/OPTIONS/Makefile.g++_openmpi
        make yes-kspace
        make yes-extra-pair
        make yes-manybody
        make yes-user-gfmd
        make g++_openmpi
        cd USER-GFMD
        make unittests

    - name: Run tests
      run: |
        $TRAVIS_BUILD_DIR/LAMMPS/src/USER-GFMD/unittests
        cd tests
        bash run_tests.sh $TRAVIS_BUILD_DIR/LAMMPS/src/lmp_g++_openmpi
